CommitMsg:
  CapitalizedSubject:
    enabled: false

  EmptyMessage:
    enabled: false

PreCommit:
  ALL:
    on_warn: fail

  AuthorEmail:
    enabled: true

  AuthorName:
    enabled: true

  MergeConflicts:
    enabled: true
    
  YamlSyntax:
    enabled: true
    
  BundleCheck:
    enabled: true

  ErbLint:
    enabled: true

  RuboCop:
    enabled: true
    problem_on_unmodified_line: ignore 
